apiVersion: v1
kind: Service
metadata:
  name: xero-grad-days-service
spec:
  ports:
    - port: 80
      targetPort: 8080 # Matches the HTTP port exposed in your app
      protocol: TCP
      name: http
  selector:
    app: xero-grad-days
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xero-grad-days-ingress
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 16m
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: xero-grad-days-service
                port:
                  number: 80


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xero-grad-days-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xero-grad-days
  template:
    metadata:
      labels:
        app: xero-grad-days
    spec:
      containers:
        - name: xero-grad-days
          image: image-tag-latest
          ports:
            - containerPort: 8080 # Matches the port used in the app
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          
          resources:
            limits:
              memory: 1024Mi
            requests:
              memory: 256Mi

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: xero-grad-days-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: xero-grad-days-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
